name: Test Artifact Upload
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Add this checkout step
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: .
