name: Test Artifact Upload

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload Artifact
        uses: actions/upload-artifact@v2  
        with:
          name: test-artifact
          path: .
